const worldinit = [
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ],
  [
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 },
    { space: "normal", color: "default", cost: 1 }
  ]
];

export default worldinit;
